Update retinol-resurfacing-serum-1-0.njk
Adding missing single quote which was causing a build error for me locally.

```
> eleventy

Problem writing Eleventy templates: (more in DEBUG output)
> unexpected end of the stream within a single quoted scalar at line 4, column 1:
    
    ^

`YAMLException` was thrown:
    YAMLException: unexpected end of the stream within a single quoted scalar at line 4, column 1:
        
        ^
        at generateError (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
        at throwError (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
        at readSingleQuotedScalar (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:586:3)
        at composeNode (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:1364:13)
        at readBlockMapping (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
        at composeNode (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
        at readDocument (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
        at loadDocuments (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
        at load (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
        at Object.safeLoad (/private/tmp/alumiermd/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
Wrote 0 files in 0.12 seconds (v0.12.1)
```